if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls="ls --color=auto"
    alias dir="dir --color=auto"
    alias vdir="vdir --color=auto"

    alias grep="grep --color=auto"
    alias fgrep="fgrep --color=auto"
    alias egrep="egrep --color=auto"
fi

# some more ls aliases
alias ll="ls -l"
alias la="ls -A"
alias l="ls -CF"

# server
alias reap="sudo service apache2 restart"

# symfony
alias symfony="app/console"
alias symfony-symlink="app/console assets:install --symlink web"
alias symfony-assetic-dump="app/console assetic:dump --env=dev --no-debug"
alias symfony-cc="app/console cache:clear --env=dev --no-debug"
alias symfony-create-db="app/console doctrine:database:create"
alias symfony-drop-db="app/console doctrine:database:drop --force"
alias symfony-migrations-diff="app/console doctrine:migrations:diff"
alias symfony-migrations-migrate="app/console doctrine:migrations:migrate"
